/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.MenuPrincipal;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGrado6 = new javax.swing.JLabel();
        txtGrado6 = new javax.swing.JTextField();
        lblGrado5 = new javax.swing.JLabel();
        txtGrado5 = new javax.swing.JTextField();
        lblGrado4 = new javax.swing.JLabel();
        txtGrado4 = new javax.swing.JTextField();
        lblGrado3 = new javax.swing.JLabel();
        txtGrado3 = new javax.swing.JTextField();
        lblGrado2 = new javax.swing.JLabel();
        txtGrado2 = new javax.swing.JTextField();
        lblGrado1 = new javax.swing.JLabel();
        txtGrado1 = new javax.swing.JTextField();
        lblConstante = new javax.swing.JLabel();
        txtConstante = new javax.swing.JTextField();
        lblPorcentajeError = new javax.swing.JLabel();
        txtPorcentajeError = new javax.swing.JTextField();
        lblIntervaloA = new javax.swing.JLabel();
        txtIntervaloA = new javax.swing.JTextField();
        lblIntervaloB = new javax.swing.JLabel();
        txtIntervaloB = new javax.swing.JTextField();
        lblDecimales = new javax.swing.JLabel();
        cbDecimales = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Metodo Secante");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        lblGrado6.setText("Grado 6");
        getContentPane().add(lblGrado6);
        lblGrado6.setBounds(20, 30, 52, 18);
        getContentPane().add(txtGrado6);
        txtGrado6.setBounds(20, 60, 110, 24);

        lblGrado5.setText("Grado 5");
        getContentPane().add(lblGrado5);
        lblGrado5.setBounds(170, 30, 52, 18);
        getContentPane().add(txtGrado5);
        txtGrado5.setBounds(170, 60, 120, 24);

        lblGrado4.setText("Grado 4");
        getContentPane().add(lblGrado4);
        lblGrado4.setBounds(320, 30, 52, 18);
        getContentPane().add(txtGrado4);
        txtGrado4.setBounds(320, 60, 130, 24);

        lblGrado3.setText("Grado 3");
        getContentPane().add(lblGrado3);
        lblGrado3.setBounds(20, 120, 52, 18);
        getContentPane().add(txtGrado3);
        txtGrado3.setBounds(20, 150, 110, 24);

        lblGrado2.setText("Grado 2");
        getContentPane().add(lblGrado2);
        lblGrado2.setBounds(170, 120, 52, 18);
        getContentPane().add(txtGrado2);
        txtGrado2.setBounds(170, 150, 120, 24);

        lblGrado1.setText("Grado 1");
        getContentPane().add(lblGrado1);
        lblGrado1.setBounds(320, 120, 52, 18);
        getContentPane().add(txtGrado1);
        txtGrado1.setBounds(320, 150, 130, 24);

        lblConstante.setText("Constante");
        getContentPane().add(lblConstante);
        lblConstante.setBounds(20, 210, 110, 18);
        getContentPane().add(txtConstante);
        txtConstante.setBounds(20, 240, 130, 24);

        lblPorcentajeError.setText("Porcentaje de error");
        getContentPane().add(lblPorcentajeError);
        lblPorcentajeError.setBounds(20, 290, 140, 18);
        getContentPane().add(txtPorcentajeError);
        txtPorcentajeError.setBounds(20, 330, 150, 24);

        lblIntervaloA.setText("Intervalo A");
        getContentPane().add(lblIntervaloA);
        lblIntervaloA.setBounds(230, 210, 80, 18);

        txtIntervaloA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntervaloAActionPerformed(evt);
            }
        });
        getContentPane().add(txtIntervaloA);
        txtIntervaloA.setBounds(220, 240, 120, 24);

        lblIntervaloB.setText("Intervalo B");
        getContentPane().add(lblIntervaloB);
        lblIntervaloB.setBounds(400, 210, 68, 18);
        getContentPane().add(txtIntervaloB);
        txtIntervaloB.setBounds(400, 240, 110, 24);

        lblDecimales.setText("Decimales a trabajar");
        getContentPane().add(lblDecimales);
        lblDecimales.setBounds(20, 380, 150, 18);

        cbDecimales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(cbDecimales);
        cbDecimales.setBounds(40, 410, 72, 24);

        btnCalcular.setText("Calcular");
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(30, 480, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIntervaloAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntervaloAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntervaloAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbDecimales;
    private javax.swing.JLabel lblConstante;
    private javax.swing.JLabel lblDecimales;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblGrado2;
    private javax.swing.JLabel lblGrado3;
    private javax.swing.JLabel lblGrado4;
    private javax.swing.JLabel lblGrado5;
    private javax.swing.JLabel lblGrado6;
    private javax.swing.JLabel lblIntervaloA;
    private javax.swing.JLabel lblIntervaloB;
    private javax.swing.JLabel lblPorcentajeError;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtIntervaloA;
    private javax.swing.JTextField txtIntervaloB;
    private javax.swing.JTextField txtPorcentajeError;
    // End of variables declaration//GEN-END:variables
}
